### ISSUE TITLE
has() relationship not working

### ISSUE THREAD

**Issue by xaviapa** [topclaudy/compoships#4] opened 2018-05-02 15:10 UTC
After defining a relationship like 
`
    public function locales()
    {
        return $this->hasMany(
            ProgramsVersionsLocale::class,
            ['id_program', 'id_version'],
            ['id_program', 'id_version']
        );
    }
`
we get the following error: 
`PHP Notice:  Array to string conversion in /opt/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php on line 393`

The error is related with `getQualidiedKeyName()` that is an array, but it expects a string. Furthermore it is not possible to be used as static, so I need to do something like `ProgramsVersion::query()->has('locales')->get();` instead of `ProgramsVersion::has('locales')->get();`

How could I do this work?

Thanks beforehand!

**Comment by topclaudy** [comment] 2018-05-02 16:16
Did you use Compoships for both models? If no, check this issue https://github.com/topclaudy/compoships/issues/1

**Comment by xaviapa** [comment] 2018-05-03 07:34
Yes I did, I'm using it in all the models.

**Comment by topclaudy** [comment] 2018-05-03 12:39
Can you show the (partial) code of your models?

**Comment by xaviapa** [comment] 2018-05-03 13:34
`
namespace App;

use Awobaz\Compoships\Database\Eloquent\Model as Eloquent;

abstract class Model extends Eloquent
{
}
`
`
namespace App;

class ProgramsVersion extends Model
{
    protected $table = 'programs_versions';

    protected $fillable = [
       ...
    ];

    public function locales()
    {
        return $this->hasMany(
            ProgramsVersionsLocale::class,
            ['id_program', 'id_version'],
            ['id_program', 'id_version']
        );
    }
}
`
`
namespace App;

class ProgramsVersionsLocale extends Model
{
    protected $table = 'programs_versions_locales';

    protected $fillable = [
        ...
    ];
}
`
`

use App\ProgramsVersion;
use Joskfg\GraphQLBulk\Interfaces\DeferredResolverInterface;

class VersionResolver implements DeferredResolverInterface
{
    public function fetch($programs, $args, $context, $info)
    {
        return ProgramsVersion::query()
            ->has('locales')
            ->get();
        }
    }
}
`

Query:
`
query {
  program(id: "<uuid>") {
    id_program
    versions {
      id_version
      locales {
        id_locale
      }
    }
  }
}
`
Result:
`
{
  "data": {
    "program": {
      "id_program": "<uuid>",
      "versions": null
    }
  },
  "errors": [
    {
      "message": "Array to string conversion",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ]
    }
  ]
}
`

**Comment by topclaudy** [comment] 2018-05-04 01:14
I'm unable to reproduce your issue. `ProgramsVersion::has('locales')->get()` should work fine.

**Comment by xaviapa** [comment] 2018-05-04 06:26
This is the other issue, the `has()` method cannot be called static, see https://github.com/topclaudy/compoships/blob/master/src/Database/Eloquent/Concerns/QueriesRelationships.php
The error I get is:
`Non-static method Awobaz\\Compoships\\Database\\Eloquent\\Model::has() should not be called statically`

**Comment by topclaudy** [comment] 2018-05-10 16:03
Going to close this - let me know if you're still having trouble with it! :)

**Comment by xaviapa** [comment] 2018-05-17 19:27
Yes, I've tried it many times but don't get how could it work. I left it and implemented a different approach without the has(), but would be nice if we could find a solution.

**Comment by topclaudy** [comment] 2018-05-17 19:38
Which version of Compoships are you using? I just tried to use `whereHas` with Compoships and It worked.

**Comment by xaviapa** [comment] 2018-05-18 07:02
The last one, 1.0.2

**Comment by topclaudy** [comment] 2018-05-22 17:56
See https://github.com/topclaudy/compoships/issues/5

**Closed by topclaudy** 2018-05-22 17:56 UTC
Labels: bug

**Comment by topclaudy** [comment] 2018-05-24 12:28
Nice catch @xaviapa
I just published a release to support version 5.4 of illuminate/database. Check version 1.0.4
Thanks.

**Comment by xaviapa** [comment] 2018-05-24 13:55
Thank you!

**Comment by ccarstens** [comment] 2018-05-26 17:46
@xaviapa omg nice, thank you!
@topclaudy thank you a lot for fixing this, and again for creating compoships in the first place! Propels my project by quite a bit! :)
