### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by kitloong** [topclaudy/compoships#152] opened 2023-02-01 13:47 UTC
I am getting the following error when trying to test my Laravel 10 support with `awobaz/compoships` as a dependency.

```
awobaz/compoships dev-master requires illuminate/database >=5.6 <=10.0 -> found illuminate/database[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (10.x-dev).
```

In [composer.json](https://github.com/topclaudy/compoships/blob/f00428ff6e18c3ebba060b45047ca4474252032f/composer.json#L16-L18) the version is defined as below:

```
"require": {
    "illuminate/database": ">=5.6 <=10.0"
},
```

I am not sure but it seems `<=10.0` does not match `10.x-dev`, `v10.0.1`, and above?

**Comment by erikn69** [comment] 2023-02-01 13:57
Duplicate of #145
Already handled by #150, read other Issues, PRs, Discussions before opening a new one

**Closed** 2023-02-01 14:01 UTC

**Comment by parallels999** [comment] 2023-02-01 14:03
@topclaudy please make a release for packagist

**Comment by topclaudy** [comment] 2023-02-01 14:12
@parallels999 2.2.0 released!

**Comment by parallels999** [comment] 2023-02-01 14:14
@topclaudy thank you very much

**Comment by kitloong** [comment] 2023-02-03 09:12
Actually, this issue is not a duplicate of @145 from what I have described with the error message.

```
"minimum-stability": "dev",
"prefer-stable": false,
```
This is assumed that the composer couldn't find the `dev-master` however the composer [documentation](https://getcomposer.org/doc/04-schema.md#prefer-stable) has explained this is not the case. (And the error message provided also stated the same thing.)

> If you require a dev version or only alphas are available for a package, those will still be selected granted that the minimum-stability allows for it.

This issue is about the version constraint defined by the package doesn't match version 10.
So even after the `2.2.0` was released, the Laravel 10 project still can't install compoship.

Steps to reproduce:

1. `git clone https://github.com/laravel/laravel.git`
2. `cd laravel && git checkout master`
3. `composer require awobaz/compoships`

Produce
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    ...
    - awobaz/compoships[dev-master, 2.2.0] require illuminate/database >=5.6 <=10.0 -> found illuminate/database[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires awobaz/compoships * -> satisfiable by awobaz/compoships[dev-master, 1.0.0, ..., 1.1.18, 2.0.0, ..., 2.2.0, 9999999-dev].
   ...
```

**Comment by parallels999** [comment] 2023-02-03 13:33
https://github.com/topclaudy/compoships/actions/runs/4065240923/jobs/6999678812

**Comment by kitloong** [comment] 2023-02-03 14:11
Okay... Just leaving this for reference (taking v9 as an example) https://semver.madewithlove.com/?package=illuminate%2Fdatabase&constraint=%3E%3D5.6+%3C%3D9.0&stability=stable

**Comment by erikn69** [comment] 2023-02-03 14:18
@kitloong thanks, review #153
